from datetime import timedelta
from uuid import uuid4

from app.core.enums import (
    AlertSeverity,
    AlertStatus,
    IncidentStatus,
    IntegrationHealth,
    IntegrationTool,
    ResponseActionMode,
    ResponseActionStatus,
    ResponseActionType,
    UserRole,
)
from app.core.security import get_password_hash
from app.utils.time import utc_now

REFERENCE_TIME = utc_now()


def hours_ago(value: int):
    return REFERENCE_TIME - timedelta(hours=value)


def days_ago(value: int):
    return REFERENCE_TIME - timedelta(days=value)


DEMO_USERS: list[dict] = [
    {
        "id": "user-admin",
        "full_name": "AegisCore Admin",
        "email": "admin@aegiscore.local",
        "password_hash": get_password_hash("password"),
        "role": UserRole.ADMIN,
        "is_active": True,
        "created_at": days_ago(180),
    },
    {
        "id": "user-analyst",
        "full_name": "AegisCore Analyst",
        "email": "analyst@aegiscore.local",
        "password_hash": get_password_hash("password"),
        "role": UserRole.ANALYST,
        "is_active": True,
        "created_at": days_ago(120),
    },
    {
        "id": "user-analyst-2",
        "full_name": "Amaya Silva",
        "email": "amaya.silva@aegiscore.local",
        "password_hash": get_password_hash("password"),
        "role": UserRole.ANALYST,
        "is_active": True,
        "created_at": days_ago(75),
    },
    {
        "id": "user-analyst-3",
        "full_name": "Maneesha Perera",
        "email": "maneesha.perera@aegiscore.local",
        "password_hash": get_password_hash("password"),
        "role": UserRole.ANALYST,
        "is_active": True,
        "created_at": days_ago(60),
    },
    {
        "id": "user-viewer",
        "full_name": "AegisCore Viewer",
        "email": "viewer@aegiscore.local",
        "password_hash": get_password_hash("password"),
        "role": UserRole.VIEWER,
        "is_active": True,
        "created_at": days_ago(90),
    },
]

DEMO_ALERTS: list[dict] = [
    {
        "id": "alert-001",
        "title": "Repeated SSH authentication failures",
        "description": "Wazuh detected repeated failed SSH attempts against a lab web host.",
        "source": "lab-web-01",
        "source_tool": "wazuh",
        "severity": AlertSeverity.HIGH,
        "status": AlertStatus.NEW,
        "confidence_score": 0.91,
        "created_at": hours_ago(3),
    },
    {
        "id": "alert-002",
        "title": "Unusual DNS request burst",
        "description": "Suricata observed DNS volume above the current baseline.",
        "source": "sensor-east-02",
        "source_tool": "suricata",
        "severity": AlertSeverity.MEDIUM,
        "status": AlertStatus.TRIAGED,
        "confidence_score": 0.74,
        "created_at": hours_ago(5),
    },
    {
        "id": "alert-003",
        "title": "Unexpected privileged RDP session after hours",
        "description": "Wazuh logged an administrative RDP session outside the scheduled lab exercise window.",
        "source": "lab-domain-01",
        "source_tool": "wazuh",
        "severity": AlertSeverity.CRITICAL,
        "status": AlertStatus.INVESTIGATING,
        "confidence_score": 0.96,
        "created_at": hours_ago(8),
    },
    {
        "id": "alert-004",
        "title": "Imported Nmap scan shows exposed admin service",
        "description": "Authorized Nmap result ingestion flagged an exposed management port for analyst review.",
        "source": "lab-gateway-01",
        "source_tool": "nmap",
        "severity": AlertSeverity.CRITICAL,
        "status": AlertStatus.TRIAGED,
        "confidence_score": 0.88,
        "created_at": hours_ago(11),
    },
    {
        "id": "alert-005",
        "title": "Hydra simulation produced repeated credential hits",
        "description": "Imported Hydra lab output crossed the configured threshold for repeated password matches.",
        "source": "simulation-node-01",
        "source_tool": "hydra",
        "severity": AlertSeverity.HIGH,
        "status": AlertStatus.RESOLVED,
        "confidence_score": 0.79,
        "created_at": hours_ago(14),
    },
    {
        "id": "alert-007",
        "title": "Suricata lateral movement signature observed",
        "description": "Network telemetry matched an SMB lateral movement pattern within the lab segment.",
        "source": "file-lab-02",
        "source_tool": "suricata",
        "severity": AlertSeverity.HIGH,
        "status": AlertStatus.INVESTIGATING,
        "confidence_score": 0.87,
        "created_at": hours_ago(27),
    },
    {
        "id": "alert-008",
        "title": "Malware quarantine event awaiting validation",
        "description": "Wazuh reported a quarantine action from endpoint tooling that needs analyst confirmation.",
        "source": "endpoint-lab-07",
        "source_tool": "wazuh",
        "severity": AlertSeverity.CRITICAL,
        "status": AlertStatus.NEW,
        "confidence_score": 0.93,
        "created_at": hours_ago(32),
    },
    {
        "id": "alert-009",
        "title": "Safe Nmap import found new service exposure",
        "description": "Authorized Nmap results showed a newly exposed service compared with the previous scan baseline.",
        "source": "lab-gateway-01",
        "source_tool": "nmap",
        "severity": AlertSeverity.MEDIUM,
        "status": AlertStatus.RESOLVED,
        "confidence_score": 0.71,
        "created_at": hours_ago(40),
    },
    {
        "id": "alert-010",
        "title": "Hydra import exceeded lockout threshold",
        "description": "A safe credential-testing simulation generated enough failures to cross the lockout watch threshold.",
        "source": "simulation-node-01",
        "source_tool": "hydra",
        "severity": AlertSeverity.LOW,
        "status": AlertStatus.TRIAGED,
        "confidence_score": 0.61,
        "created_at": hours_ago(51),
    },
    {
        "id": "alert-012",
        "title": "Privilege escalation command logged",
        "description": "Wazuh recorded command activity consistent with a lab privilege escalation exercise.",
        "source": "endpoint-lab-04",
        "source_tool": "wazuh",
        "severity": AlertSeverity.HIGH,
        "status": AlertStatus.TRIAGED,
        "confidence_score": 0.84,
        "created_at": hours_ago(76),
    },
    {
        "id": "alert-013",
        "title": "TLS fingerprint mismatch against baseline",
        "description": "Suricata detected a JA3 fingerprint that does not align with the current baseline.",
        "source": "sensor-west-01",
        "source_tool": "suricata",
        "severity": AlertSeverity.MEDIUM,
        "status": AlertStatus.INVESTIGATING,
        "confidence_score": 0.73,
        "created_at": hours_ago(92),
    },
    {
        "id": "alert-014",
        "title": "Suspicious sudoers file change",
        "description": "Wazuh observed a change to sudoers content during a hardening validation exercise.",
        "source": "endpoint-lab-09",
        "source_tool": "wazuh",
        "severity": AlertSeverity.HIGH,
        "status": AlertStatus.RESOLVED,
        "confidence_score": 0.81,
        "created_at": hours_ago(110),
    },
    {
        "id": "alert-015",
        "title": "Outbound beaconing rehearsal traffic",
        "description": "Suricata flagged beacon-like traffic generated by a controlled validation simulation.",
        "source": "sensor-east-02",
        "source_tool": "suricata",
        "severity": AlertSeverity.MEDIUM,
        "status": AlertStatus.NEW,
        "confidence_score": 0.7,
        "created_at": hours_ago(128),
    },
    {
        "id": "alert-017",
        "title": "Suspicious cron persistence entry",
        "description": "Wazuh detected a new cron entry created during a persistence simulation lab.",
        "source": "endpoint-lab-05",
        "source_tool": "wazuh",
        "severity": AlertSeverity.HIGH,
        "status": AlertStatus.NEW,
        "confidence_score": 0.86,
        "created_at": hours_ago(160),
    },
    {
        "id": "alert-018",
        "title": "Imported Nmap results show unexpected high ports",
        "description": "Safe Nmap lab parsing identified additional exposed services requiring analyst validation.",
        "source": "lab-gateway-02",
        "source_tool": "nmap",
        "severity": AlertSeverity.MEDIUM,
        "status": AlertStatus.TRIAGED,
        "confidence_score": 0.72,
        "created_at": hours_ago(167),
    },
]

DEMO_INCIDENTS: list[dict] = [
    {
        "id": "incident-001",
        "alert_id": "alert-003",
        "assigned_to_user_id": "user-analyst",
        "priority": AlertSeverity.CRITICAL,
        "status": IncidentStatus.IN_PROGRESS,
        "notes": "Validate whether the after-hours administrative session was expected in the active lab scenario.",
        "title": "After-hours privileged access review",
        "summary": "Confirm the unexpected RDP session timeline, source account, and host activity before closing the case.",
        "affected_asset": "lab-domain-01",
        "updated_at": hours_ago(2),
        "opened_at": hours_ago(7),
        "closed_at": None,
    },
    {
        "id": "incident-002",
        "alert_id": "alert-004",
        "assigned_to_user_id": "user-analyst-2",
        "priority": AlertSeverity.CRITICAL,
        "status": IncidentStatus.TRIAGED,
        "notes": "Review the exposed management service from safe Nmap import results and document containment options.",
        "title": "Management port exposure validation",
        "summary": "Analysts are verifying whether the exposed service belongs to the approved training topology or needs remediation.",
        "affected_asset": "lab-gateway-01",
        "updated_at": hours_ago(6),
        "opened_at": hours_ago(11),
        "closed_at": None,
    },
    {
        "id": "incident-003",
        "alert_id": "alert-007",
        "assigned_to_user_id": None,
        "priority": AlertSeverity.HIGH,
        "status": IncidentStatus.OPEN,
        "notes": "Awaiting analyst assignment for SMB movement review across the file segment.",
        "title": "Possible lateral movement review",
        "summary": "Suricata telemetry suggests east-west movement patterns that need case ownership before deeper correlation.",
        "affected_asset": "file-lab-02",
        "updated_at": hours_ago(18),
        "opened_at": hours_ago(27),
        "closed_at": None,
    },
    {
        "id": "incident-004",
        "alert_id": "alert-008",
        "assigned_to_user_id": "user-analyst",
        "priority": AlertSeverity.CRITICAL,
        "status": IncidentStatus.RESOLVED,
        "notes": "Quarantine evidence and endpoint timeline were verified against the malware handling lab notes.",
        "title": "Endpoint quarantine verification",
        "summary": "The quarantine event aligned with the controlled malware analysis exercise and has been closed with evidence.",
        "affected_asset": "endpoint-lab-07",
        "updated_at": hours_ago(24),
        "opened_at": hours_ago(31),
        "closed_at": hours_ago(24),
    },
    {
        "id": "incident-005",
        "alert_id": "alert-012",
        "assigned_to_user_id": "user-analyst-3",
        "priority": AlertSeverity.HIGH,
        "status": IncidentStatus.IN_PROGRESS,
        "notes": "Correlate privilege escalation commands with the active hardening lab worksheet and analyst narrative.",
        "title": "Privilege escalation command review",
        "summary": "The team is tracing command execution context to confirm the event stays within the approved lab exercise scope.",
        "affected_asset": "endpoint-lab-04",
        "updated_at": hours_ago(30),
        "opened_at": hours_ago(76),
        "closed_at": None,
    },
]

DEMO_RESPONSE_ACTIONS: list[dict] = [
    {
        "id": "response-001",
        "alert_id": "alert-003",
        "action_type": ResponseActionType.CREATE_INCIDENT,
        "status": ResponseActionStatus.COMPLETED,
        "execution_mode": ResponseActionMode.MANUAL,
        "target_label": "incident-001",
        "notes": "Analyst escalated the privileged access alert into the incident workflow.",
        "result_summary": "Incident incident-001 was opened for analyst review.",
        "performed_by_user_id": "user-admin",
        "performed_by_name": "AegisCore Admin",
        "incident_id": "incident-001",
        "created_at": hours_ago(7),
    },
    {
        "id": "response-002",
        "alert_id": "alert-003",
        "action_type": ResponseActionType.MARK_INVESTIGATING,
        "status": ResponseActionStatus.COMPLETED,
        "execution_mode": ResponseActionMode.MANUAL,
        "target_label": "investigating",
        "notes": "Analyst moved the privileged access alert into investigation.",
        "result_summary": "Alert status updated to investigating.",
        "performed_by_user_id": "user-admin",
        "performed_by_name": "AegisCore Admin",
        "incident_id": "incident-001",
        "created_at": hours_ago(7),
    },
    {
        "id": "response-003",
        "alert_id": "alert-004",
        "action_type": ResponseActionType.ISOLATE_ASSET,
        "status": ResponseActionStatus.COMPLETED,
        "execution_mode": ResponseActionMode.MANUAL,
        "target_label": "lab-gateway-01",
        "notes": "Containment rehearsal recorded for the exposed management service finding.",
        "result_summary": "Asset lab-gateway-01 was recorded as isolated in the lab-only response log.",
        "performed_by_user_id": "user-admin",
        "performed_by_name": "AegisCore Admin",
        "incident_id": "incident-002",
        "created_at": hours_ago(10),
    },
]

DEMO_BLOCKED_IPS: list[dict] = []

DEMO_DISABLED_ACCOUNTS: list[dict] = []

DEMO_ISOLATED_ASSETS: list[dict] = [
    {
        "asset": "lab-gateway-01",
        "alert_id": "alert-004",
        "created_at": hours_ago(10),
        "created_by_user_id": "user-admin",
        "execution_mode": ResponseActionMode.MANUAL,
    }
]

DEMO_LOGS: list[dict] = [
    {
        "id": "log-001",
        "source": "lab-web-01",
        "source_tool": "wazuh",
        "raw_log": {
            "timestamp": hours_ago(3).isoformat(),
            "host": "lab-web-01",
            "message": "Failed password for invalid user analyst from 10.0.0.22",
            "rule": "sshd",
            "user": "analyst",
            "source_ip": "10.0.0.22",
            "severity": "high",
        },
        "normalized_log": {
            "timestamp": hours_ago(3).isoformat(),
            "severity": "high",
            "event_type": "authentication",
            "source": "lab-web-01",
            "source_tool": "wazuh",
            "message": "Failed password for invalid user analyst from 10.0.0.22",
            "observables": {"actor": "analyst", "source_ip": "10.0.0.22"},
            "original_keys": ["host", "message", "rule", "severity", "source_ip", "timestamp", "user"],
        },
        "event_type": "authentication",
        "severity": AlertSeverity.HIGH,
        "created_at": hours_ago(3),
    },
    {
        "id": "log-002",
        "source": "sensor-east-02",
        "source_tool": "suricata",
        "raw_log": {
            "timestamp": hours_ago(5).isoformat(),
            "sensor": "sensor-east-02",
            "message": "ET POLICY Suspicious DNS query burst observed.",
            "signature": "DNS burst",
            "query_count": 240,
            "src_ip": "10.10.20.14",
            "dest_ip": "8.8.8.8",
            "severity": "medium",
        },
        "normalized_log": {
            "timestamp": hours_ago(5).isoformat(),
            "severity": "medium",
            "event_type": "network",
            "source": "sensor-east-02",
            "source_tool": "suricata",
            "message": "ET POLICY Suspicious DNS query burst observed.",
            "observables": {"source_ip": "10.10.20.14", "destination_ip": "8.8.8.8"},
            "original_keys": ["dest_ip", "message", "query_count", "sensor", "severity", "signature", "src_ip", "timestamp"],
        },
        "event_type": "network",
        "severity": AlertSeverity.MEDIUM,
        "created_at": hours_ago(5),
    },
    {
        "id": "log-003",
        "source": "lab-gateway-01",
        "source_tool": "nmap",
        "raw_log": {
            "timestamp": hours_ago(11).isoformat(),
            "asset": "lab-gateway-01",
            "message": "Imported lab Nmap result identified tcp/8443 open on gateway host.",
            "port": 8443,
            "protocol": "tcp",
            "state": "open",
            "service": "https-alt",
            "severity": "medium",
        },
        "normalized_log": {
            "timestamp": hours_ago(11).isoformat(),
            "severity": "medium",
            "event_type": "scan_result",
            "source": "lab-gateway-01",
            "source_tool": "nmap",
            "message": "Imported lab Nmap result identified tcp/8443 open on gateway host.",
            "observables": {"port": 8443},
            "original_keys": ["asset", "message", "port", "protocol", "service", "severity", "state", "timestamp"],
        },
        "event_type": "scan_result",
        "severity": AlertSeverity.MEDIUM,
        "created_at": hours_ago(11),
    },
    {
        "id": "log-004",
        "source": "simulation-node-01",
        "source_tool": "hydra",
        "raw_log": {
            "timestamp": hours_ago(14).isoformat(),
            "asset": "simulation-node-01",
            "message": "Imported Hydra lab result recorded repeated password matches for test accounts.",
            "username": "student_admin",
            "attempts": 12,
            "severity": "high",
        },
        "normalized_log": {
            "timestamp": hours_ago(14).isoformat(),
            "severity": "high",
            "event_type": "credential_assessment",
            "source": "simulation-node-01",
            "source_tool": "hydra",
            "message": "Imported Hydra lab result recorded repeated password matches for test accounts.",
            "observables": {"actor": "student_admin"},
            "original_keys": ["asset", "attempts", "message", "severity", "timestamp", "username"],
        },
        "event_type": "credential_assessment",
        "severity": AlertSeverity.HIGH,
        "created_at": hours_ago(14),
    },
]

DEMO_INTEGRATIONS: list[dict] = [
    {
        "id": "integration-001",
        "tool_name": IntegrationTool.WAZUH,
        "status": IntegrationHealth.CONNECTED,
        "last_sync_at": hours_ago(1),
        "notes": "Primary endpoint telemetry source.",
        "last_import_at": hours_ago(1),
        "last_import_message": "Wazuh alerts are available for dashboard and workflow review.",
    },
    {
        "id": "integration-002",
        "tool_name": IntegrationTool.SURICATA,
        "status": IntegrationHealth.CONNECTED,
        "last_sync_at": hours_ago(1),
        "notes": "Primary network alert source.",
        "last_import_at": hours_ago(1),
        "last_import_message": "Seeded Suricata lab network alerts available for alert and log workflows.",
    },
    {
        "id": "integration-003",
        "tool_name": IntegrationTool.NMAP,
        "status": IntegrationHealth.CONNECTED,
        "last_sync_at": hours_ago(10),
        "notes": "Authorized assessment result ingestion for scan findings. No offensive automation.",
        "last_import_at": hours_ago(10),
        "last_import_message": "Seeded Nmap lab assessment findings are available for dashboard and alert review.",
    },
    {
        "id": "integration-004",
        "tool_name": IntegrationTool.HYDRA,
        "status": IntegrationHealth.CONNECTED,
        "last_sync_at": hours_ago(9),
        "notes": "Authorized credential-assessment result ingestion. No offensive automation.",
        "last_import_at": hours_ago(9),
        "last_import_message": "Seeded Hydra lab credential-assessment findings are available for dashboard and alert review.",
    },
]


def build_user_record(full_name: str, email: str, password_hash: str, role: UserRole) -> dict:
    return {
        "id": f"user-{uuid4()}",
        "full_name": full_name,
        "email": email,
        "password_hash": password_hash,
        "role": role,
        "is_active": True,
        "created_at": utc_now(),
    }
