import { DataTable } from "@/components/DataTable";
import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { reportRows } from "@/data/mock";

const columns = [
  { key: "id", label: "Report ID" },
  { key: "name", label: "Report name" },
  { key: "type", label: "Type" },
  { key: "status", label: "Status" },
  { key: "generatedBy", label: "Generated by" },
  { key: "schedule", label: "Schedule" }
];

export function ReportsPage() {
  const rows = reportRows.map((report) => ({
    ...report,
    status: (
      <StatusBadge variant={report.status === "ready" ? "connected" : "pending"}>
        {report.status}
      </StatusBadge>
    )
  }));

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Reporting"
        title="Reports"
        description="A clean reporting area for presentation exports, incident summaries, and model insights."
        action={<button className="btn-primary">New report</button>}
      />

      <DataTable columns={columns} rows={rows} />
    </div>
  );
}
